name: Build and Push to Amazon ECR

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - run: echo "Checkout source code"
      - name: Checkout source code
        uses: actions/checkout@v4

      # Step 1: Checkout the repository
      - name: Debug Secrets
        run: echo "aws-region ${{ secrets.AWS_REGION }}"

      # Step 1: Checkout the repository
      - name: Debug Secrets
        run: echo "AWS_ACCESS_KEY_ID ${{ secrets.AWS_ACCESS_KEY_ID }}"

      # Step 1: Checkout the repository
      - name: Debug Secrets
        run: echo "AWS_SECRET_ACCESS_KEY ${{ secrets.AWS_SECRET_ACCESS_KEY }}"


      # Step 2: Log in to Amazon ECR
      - run: echo "Log in to Amazon ECR"
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Build the Docker image
      - run: echo "Build Docker image"
      - name: Build Docker image
        run: |
          docker build -t exchange-rate-react .
          docker tag exchangerate-react:latest 741448956915.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/er/exchangerate-react:latest

      # Step 4: Push the Docker image to Amazon ECR
      - run: echo "Push Docker image to Amazon ECR"
      - name: Push Docker image to Amazon ECR
        run: |
          docker push 741448956915.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/er/exchangerate-react:latest
      - run: echo "Complete"
